apiVersion: v1
kind: Service
metadata:
  name: ggj-content-service
spec:
  selector:
    app: ggj-content-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
